-- MySQL Script generated by MySQL Workbench
-- Jum 05 Peb 2016 08:32:54  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sipp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `user_full_name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `user_password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `user_email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `user_description` TEXT NULL DEFAULT NULL COMMENT '',
  `user_role_role_id` INT(11) NULL COMMENT '',
  `user_is_deleted` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `user_input_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `user_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_user_user_role1_idx` (`user_role_role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_role_id`)
    REFERENCES `user_role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `activity_log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `log_date` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `log_action` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `log_module` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `log_info` TEXT NULL DEFAULT NULL COMMENT '',
  `user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`log_id`)  COMMENT '',
  INDEX `fk_g_activity_log_g_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_g_activity_log_g_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(40) NOT NULL COMMENT '',
  `ip_address` VARCHAR(45) NOT NULL COMMENT '',
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `data` BLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ci_sessions_timestamp` (`timestamp` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mediamanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `type` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `isfile` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `label` TEXT NULL DEFAULT NULL COMMENT '',
  `info` TEXT NULL DEFAULT NULL COMMENT '',
  `upload_at` DATETIME NULL DEFAULT NULL COMMENT '',
  `album_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `mediamanager_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager_album` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `label` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `upload_at` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `posts_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `posts_title` VARCHAR(255) NULL COMMENT '',
  `posts_description` TEXT NULL COMMENT '',
  `posts_image` VARCHAR(255) NULL COMMENT '',
  `posts_published_date` TIMESTAMP NULL COMMENT '',
  `posts_is_published` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `posts_category_category_id` INT NULL COMMENT '',
  `user_user_id` INT(11) NULL COMMENT '',
  `posts_input_date` TIMESTAMP NULL COMMENT '',
  `posts_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`posts_id`)  COMMENT '',
  INDEX `fk_posts_posts_category1_idx` (`posts_category_category_id` ASC)  COMMENT '',
  INDEX `fk_posts_user1_idx` (`user_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_posts_posts_category1`
    FOREIGN KEY (`posts_category_category_id`)
    REFERENCES `posts_category` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_posts_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member` (
  `member_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `member_nip` VARCHAR(255) NOT NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `member_full_name` VARCHAR(255) NULL COMMENT '',
  `member_sex` ENUM('MALE', 'FEMALE') NULL COMMENT '',
  `member_birth_place` VARCHAR(45) NULL COMMENT '',
  `member_birth_date` DATE NULL COMMENT '',
  `member_school` VARCHAR(255) NULL COMMENT '',
  `member_phone` VARCHAR(45) NULL COMMENT '',
  `member_address` TEXT NULL COMMENT '',
  `member_image` VARCHAR(100) NULL COMMENT '',
  `member_mentor` VARCHAR(255) NULL COMMENT '',
  `member_division` VARCHAR(255) NULL COMMENT '',
  `member_status` TINYINT(1) NULL DEFAULT 0 COMMENT '0=\'Non-Active\', 1=\'Active\'',
  `member_entry_date` DATE NULL COMMENT '',
  `member_end_date` DATE NULL COMMENT '',
  `member_score` VARCHAR(45) NULL COMMENT '',
  `member_input_date` TIMESTAMP NULL COMMENT '',
  `member_last_update` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`member_id`, `member_nip`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `present`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `present` (
  `present_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `present_year` YEAR NULL COMMENT '',
  `present_month` INT NULL COMMENT '',
  `present_date` DATETIME NULL COMMENT '',
  `present_entry_time` TIME NULL COMMENT '',
  `present_out_time` TIME NULL COMMENT '',
  `present_desc` ENUM('Hadir', 'Sakit', 'Izin', 'Alfa') NULL COMMENT '',
  `present_is_late` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `present_is_before` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `member_member_id` INT NULL COMMENT '',
  `member_member_nip` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`present_id`)  COMMENT '',
  INDEX `fk_present_member1_idx` (`member_member_id` ASC, `member_member_nip` ASC)  COMMENT '',
  CONSTRAINT `fk_present_member1`
    FOREIGN KEY (`member_member_id` , `member_member_nip`)
    REFERENCES `member` (`member_id` , `member_nip`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
